[package]
name = "rust-fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.63"
wasm-workers-rs = { path = "../../kits/rust" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.85"
