from bs4 import BeautifulSoup

html_doc = """<!DOCTYPE html>
<head>
  <title>Wasm Workers Server</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta charset="UTF-8">
</head>
<body>
  <main>
    <h1>Hello from Wasm Workers Server</h1>
    <p>
      This page was generated by a Python file running in WebAssembly.
    </p>
  </main>
</body>
"""

def worker(req):
    soup = BeautifulSoup(html_doc, 'html.parser')

    res = Response(soup.get_text("</br></br>", True))
    res.headers["x-generated-by"] = "wasm-workers-server"

    return res
