name: Rust release

on:
  push:
    branches: [ main ]
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"
  # TODO: For tesgting. Run this workflow only on a new release.
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Caching
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Test
      run: cargo test
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            arch: x86_64
            platform: unknown-linux-musl
            cross: false
            name: linux-musl
          - os: ubuntu-latest
            arch: aarch64
            platform: unknown-linux-musl
            cross: true
            name: linux-musl
          - os: windows-latest
            arch: x86_64
            platform: pc-windows-msvc
            cross: false
            name: pc-windows
          - os: ubuntu-latest
            arch: aarch64
            platform: pc-windows-msvc
            cross: true
            name: pc-windows
          - os: macos-latest
            arch: x86_64
            platform: apple-darwin
            cross: false
            name: macos-darwin
          - os: ubuntu-latest
            arch: aarch64
            platform: apple-darwin
            cross: true
            name: macos-darwin
    runs-on: ${{ matrix.os }}
    env:
      # We use cross for arm builds
      CARGO: cargo
    steps:
    - uses: actions/checkout@v3
    - name: Install cross
      if: matrix.cross == true
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
    - name: Install target
      if: matrix.cross == false
      run: rustup target add ${{ matrix.arch }}-${{ matrix.platform }}
    - name: Build
      run: ${{env.CARGO}} build --verbose --release --target=${{ matrix.arch }}-${{ matrix.platform }}
    - name: Tarball
      run: |
        mkdir out
        cp {README.md,LICENSE} out

        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp "target/${{ matrix.arch }}-${{ matrix.platform }}/release/wws.exe" ./out
        else
          cp "target/${{ matrix.arch }}-${{ matrix.platform }}/release/wws" ./out
        fi

        tar czf "wws-${{ matrix.name }}-${{ matrix.arch }}.tar.gz" ./out
        echo "TARBALL=wws-${{ matrix.name }}-${{ matrix.arch }}.tar.gz" >> $GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: wws-${{ matrix.name }}-${{ matrix.arch }}
        path: ${{ env.TARBALL }}
        # TODO: This is for testing
        retention-days: 7
