version = 1

[[runtimes]]
name = "ruby"
version = "3.2.0+20230215"
tags = [ "latest", "3.2.0" ]
status = "active"
args = [ "--", "/src/index.rb" ]
binary = { url = "https://github.com/vmware-labs/webassembly-language-runtimes/releases/download/ruby%2F3.2.0%2B20230215-1349da9/ruby-3.2.0.wasm", filename = "ruby.wasm", checksum = { type = "sha256", value = "1ea101553585a9ec4734ed3774648107ccd7beb6971f9ce687a084d06b8409f9" } }
extensions = [ "rb" ]
polyfill = { url = "https://workers.wasmlabs.dev/repository/files/ruby/3/poly.rb", filename = "poly.rb", checksum = { type = "sha256", value = "044b0d4bde7d3a9b0f275821fb5b67cc2e382267904df2516a23dbec1fae6bae" } }
wrapper = { url = "https://workers.wasmlabs.dev/repository/files/ruby/3/wrapper.txt", filename = "wrapper.txt", checksum = { type = "sha256", value = "6d808b4747cf30f82665a38a47e1176513bbdd6ad558c09db03d719e33ad2da0" } }

[[runtimes]]
name = "python"
version = "3.11.1+TBD"
tags = [ "latest", "3.11.1" ]
status = "active"
args = [ "--", "/src/index.py" ]
binary = { url = "TBD", filename = "python.wasm", checksum = { type = "sha256", value = "TBD" } }
extensions = [ "py" ]
polyfill = { url = "https://workers.wasmlabs.dev/repository/files/python/3/poly.py", filename = "poly.py", checksum = { type = "sha256", value = "2027b73556ca02155f026cee751ab736985917d2f28bbcad5aac928c719e1112" } }
wrapper = { url = "https://workers.wasmlabs.dev/repository/files/python/3/wrapper.txt", filename = "wrapper.txt", checksum = { type = "sha256", value = "cf1edc5b1427180ec09d18f4d169580379f1b12001f30e330759f9a0f8745357" } }